### ISSUE TITLE
Links input problem

### ISSUE THREAD

**Issue by abhinabh** [CoreyMSchafer/code_snippets#40]
How to add links( like google.com) to a post (content). I tried doing it but failed

**Comment by abhinabh** [comment]
> How to add links( like google.com) to a post (content). I tried doing it but failed

can you share the code if possible?
like if i add https://www.google.com/ in content section. it must redirect me to the google homepage

**Comment by CoreyMSchafer** [comment]
You would need to allow some type of HTML in the post content. This has been requested that I cover this, so I might try to do this in a future video. We could also set up something where we translate Markdown to HTML. There are a lot of options. I would recommend looking up how to add HTML to Flask or Django posts and read up on it there because it would be too long of an answer for me to give here.

**Comment by abhinabh** [comment]
Okay, Thank You!
Please, cover this in your future video.
